### ISSUE TITLE
Unrecognized field: name !=

### ISSUE THREAD

**Issue by ghost** [FreezyBee/DoctrineFormMapper#1]
Doctrine\ORM\ORMException Unrecognized field: name !=

`$form->addMultiSelect('values', 'Allowed values')
            ->setOption(IComponentMapper::ITEMS_TITLE, 'name')
            ->setOption(IComponentMapper::ITEMS_FILTER, ['name !=' => 'test'])
            ->setRequired(false);`

without filter it works

**Comment by janatjak** [comment]
It is just example of how you can use IComponentMapper features (filtering, sorting, custom select item texts).

**Comment by ghost** [comment]
Ik, but I wanted implement that filter, this happend.

**Comment by janatjak** [comment]
Filter ['name !=' => 'x'] works only with kdyby/doctrine.
