### ISSUE TITLE
ITEMS_FILTER criteria not working with Nettrine

### ISSUE THREAD

**Issue by jvitasek** [FreezyBee/DoctrineFormMapper#3]
Hey guys, I have a problem with this expression:

`->setOption(IComponentMapper::ITEMS_FILTER, ['column !=' => null])`

I've migrated to Nettrine from Kdyby/Doctrine and it does not work anymore. I think this is related to specifics of Kdyby/Doctrine, where you could use these advanced criteria in findBy methods etc.

Is there any other way of achieving this functionality?

**Comment by janatjak** [comment]
Nettrine doesn't support `findBy(['column !=' => null])`

`!=` is kdyby internal magic

**Comment by janatjak** [comment]
@jvitasek you can try new version [v1.4.0](https://github.com/FreezyBee/DoctrineFormMapper/releases/tag/v1.4.0)

```php
// filter items by callback
->setOption(IComponentMapper::ITEMS_FILTER, function(QueryBuilder $qb) {
    $qb->andWhere('entity.column != 0');
});
```

**Comment by jvitasek** [comment]
@janatjak that’s perfect, thanks!
