### ISSUE TITLE
Problem with periods in input values - they get replaced

### ISSUE THREAD

**Issue by jvitasek** [FreezyBee/DoctrineFormMapper#4]
Hi, I'm trying to print out e-mail addresses in a multiselect input.

```
$form->addMultiSelect('users', 'Uživatelé')->setOption(IComponentMapper::ITEMS_TITLE, 'email');
```

But the e-mail get printed like this (with all content being escaped up to the last dot):

![image](https://user-images.githubusercontent.com/8986306/118439326-0f475b00-b6e6-11eb-9654-2b2b80115c38.png)

So that the e-mail "test@test.cz" gets printed as "cz", and the e-mail "test.test@test.cz" gets printed as "test@test.cz"

I solved this temporarily by replacing all dots to commas:

```
$form->addMultiSelect('users', 'Uživatelé')
->setOption(IComponentMapper::ITEMS_TITLE, function(User $user) {
	return str_replace('.', ',', $user->getEmail());
});
```

But I would be much happier if this was resolved. This wasn't an issue before, but after updating to PHP8 and newest version of this package, this became an issue.

Could you please take a look? Thanks!

**Comment by janatjak** [comment]
Can you try to turn translator off please?

```php
$form->addMultiSelect('users', 'Uživatelé')
   ->setOption(IComponentMapper::ITEMS_TITLE, 'email')
   ->setTranslator(null);
```

**Comment by jvitasek** [comment]
@janatjak that did the trick, thanks
